// <auto-generated />
using System;
using MerhabaDunyaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerhabaDunyaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725110327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MerhabaDunyaApi.Models.EmissionFactor", b =>
                {
                    b.Property<int>("Kimlik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kimlik"));

                    b.Property<decimal>("KgCO2PerLitre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YakitTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kimlik");

                    b.ToTable("EmisyonFaktorleri", (string)null);
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Kargo", b =>
                {
                    b.Property<int>("Kimlik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kimlik"));

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiparisKimlik")
                        .HasColumnType("int");

                    b.Property<string>("TakipNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kimlik");

                    b.HasIndex("SiparisKimlik")
                        .IsUnique();

                    b.ToTable("Kargolar");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Kullanici", b =>
                {
                    b.Property<int>("Kimlik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kimlik"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Kimlik");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.KullaniciRozetleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciKimlik")
                        .HasColumnType("int");

                    b.Property<int>("RozetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerilisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciKimlik");

                    b.HasIndex("RozetId");

                    b.ToTable("KullaniciRozetleri");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Rozet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequiredSavePct")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rozetler");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Siparis", b =>
                {
                    b.Property<int>("Kimlik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kimlik"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciKimlik")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Kimlik");

                    b.HasIndex("KullaniciKimlik");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Kargo", b =>
                {
                    b.HasOne("MerhabaDunyaApi.Models.Siparis", "Siparis")
                        .WithOne("Kargo")
                        .HasForeignKey("MerhabaDunyaApi.Models.Kargo", "SiparisKimlik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.KullaniciRozetleri", b =>
                {
                    b.HasOne("MerhabaDunyaApi.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciRozetleri")
                        .HasForeignKey("KullaniciKimlik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerhabaDunyaApi.Models.Rozet", "Rozet")
                        .WithMany("KullaniciRozetleri")
                        .HasForeignKey("RozetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rozet");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Siparis", b =>
                {
                    b.HasOne("MerhabaDunyaApi.Models.Kullanici", "Kullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciKimlik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciRozetleri");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Rozet", b =>
                {
                    b.Navigation("KullaniciRozetleri");
                });

            modelBuilder.Entity("MerhabaDunyaApi.Models.Siparis", b =>
                {
                    b.Navigation("Kargo");
                });
#pragma warning restore 612, 618
        }
    }
}
